name: Radic's Gits
description: Web Developer from Somewhere
keywords: [radic,webdesign,programming,designing]

url: robin.radic.nl
encoding: utf-8
timezone: Amsterdam/Europe

# GITHUB METADATA
#https://github.com/jekyll/github-metadata
repository: RobinRadic/RobinRadic.github.io
gems:
  - jekyll-github-metadata

sgems:
  - jekyll-github-metadata
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

layouts:     ./_includes/_layouts
data_source: ./_includes/_data


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      image: "/images/abstract-1.jpg"
      comments: true
      share: true
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      hide-title: true
      share: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project
      hide-title: true
      share: true
      navigation:
        - name: Home
          link: /
          icon: fa fa-home

        - name: Project overview
          link: /:project/
          icon: fa fa-user

        - name: Demonstration
          link: /:project/demonstration
          icon: fa fa-play

        - name: Documentation
          link: /:project/documentation
          icon: fa fa-mortar-board

        - name: API
          link: /:project/api
          icon: fa fa-code



collections:
  portfolio:
    output: true;
    permalink: /portfolio/:title/
  projects:
    output: true
    permalink: /:path/

permalink:   /:categories/:title/
paginate: 5

#sass:
#  sass_dir: _sass
#  style: compressed


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "src", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "commit", "serve", "update-ghpages", ".bowerrc", "bower.json"]
